name: SonarCloud Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: Code Quality Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'backend/go.mod'

      - name: Generate Coverage Report
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=maverick0322
            -Dsonar.projectKey=maverick0322_Taskify
            -Dsonar.sources=.
            -Dsonar.coverage.exclusions=frontend/**,backend/cmd/**,backend/internal/core/ports/**
            -Dsonar.go.coverage.reportPaths=coverage.out